import { Card } from '../types';

const blackCards: Card[] = [
  { content: 'But online I read that __________.', id: 1 },
  { content: '11 reasons to __________. Nr 5 will surprise you.', id: 2 },
  { content: '9gags most upvoted post is __________.', id: 3 },
  { content: 'After successfully selling my company I now __________.', id: 4 },
  {
    content:
      'After ten years working as a developer, I am addicted to __________.',
    id: 5,
  },
  { content: 'As a hobby project I __________.', id: 6 },
  {
    content: 'Customer always complain about __________ in our software.',
    id: 7,
  },
  { content: 'Deploying my application in __________.', id: 8 },
  { content: 'Excel should be used for __________ more often.', id: 9 },
  { content: 'Fixing bugs by __________.', id: 10 },
  { content: 'For relaxing I do __________.', id: 11 },
  { content: 'High quality software is made with __________', id: 12 },
  { content: 'I am using __________ for my monolith.', id: 1 },
  { content: 'I asked my boss for a raise due to __________.', id: 13 },
  { content: 'I declined the pull request because of __________.', id: 14 },
  { content: "I don't get laid because of __________.", id: 16 },
  { content: "I don't get paid because of __________.", id: 17 },
  { content: "I don't need backups, I have __________.", id: 18 },
  { content: 'I filed a bug on __________.', id: 19 },
  { content: 'I integrated __________ into my DevSecOps pipeline.', id: 21 },
  { content: 'I like to get drunk and __________.', id: 1 },
  { content: 'I like to turn up to investor meetings __________.', id: 22 },
  { content: 'I spent my last salary on __________.', id: 23 },
  { content: 'I successfully tested __________.', id: 24 },
  { content: 'I switched to Linux because of __________.', id: 25 },
  { content: 'I would sell my shares of the company for __________.', id: 26 },
  { content: 'Last deployment failed because of __________.', id: 27 },
  { content: 'Last time I went outside, I experienced __________.', id: 28 },
  { content: 'Last year North Korea spent 10 million on __________.', id: 29 },
  { content: "My Cloud Drive won't sync because of __________.", id: 30 },
  { content: 'My alternative to the gym is __________.', id: 31 },
  { content: 'My co-worker files a complaint because of __________.', id: 32 },
  { content: 'My job feels like __________.', id: 34 },
  {
    content: 'My morning toilet session can be explained as __________.',
    id: 35,
  },
  { content: 'My security is so good, it __________.', id: 36 },
  { content: 'On my GitHub profile you will find __________.', id: 37 },
  { content: 'On our Offsite we did __________.', id: 38 },
  { content: 'Our USP is __________.', id: 39 },
  {
    content: 'Our systems for __________ runs only on raspberry pies.',
    id: 40,
  },
  { content: 'Software development is like __________.', id: 41 },
  { content: 'The 11-star user experience is __________.', id: 42 },
  { content: 'The booth is themed __________.', id: 43 },
  { content: 'The customer requests __________.', id: 44 },
  { content: 'The difference between RSA and DSA is __________.', id: 45 },
  {
    content: 'The new marketing campaign for April 1st will be __________.',
    id: 47,
  },
  { content: 'The next blog article will be about __________.', id: 48 },
  { content: 'The next superior cloud service will use __________.', id: 49 },
  { content: 'There still is a bug in __________.', id: 50 },
  { content: "This year's marketing motto is __________.", id: 51 },
  { content: 'We use __________ for quality control.', id: 52 },
  {
    content:
      "When the marketing intern asks: 'Can you please change __________ on the website'",
    id: 53,
  },
  {
    content:
      'When the sales guys are laughing in their office they are __________.',
    id: 54,
  },
  { content: 'Yesterday Bill Gates asked me __________', id: 55 },
  { content: '__________ as a Service', id: 56 },
  { content: '__________ makes the CEO happy.', id: 57 },
  { content: '__________. How did this ever work?', id: 58 },
  { content: '__________. Oh, this was earlier than expected.', id: 59 },
];

export default blackCards;