import { Card } from "../types";

const blackCards: Card[] =  [
    { content: "But online I read that \BLANK.", id: 1 },
    { content: "11 reasons to \BLANK. Nr 5 will surprise you.", id: 2 },
    { content: "9gags most upvoted post is \BLANK.", id: 3 },
    { content: "After successfully selling my company I now \BLANK.", id: 4 },
    { content: "After ten years working as a developer, I am addicted to \BLANK.", id: 5 },
    { content: "As a hobby project I \BLANK.", id: 6 },
    { content: "Customer always complain about \BLANK in our software.", id: 7 },
    { content: "Deploying my application in \BLANK.", id: 8 },
    { content: "Excel should be used for \BLANK more often.", id: 9 },
    { content: "Fixing bugs by \BLANK.", id: 10 },
    { content: "For relaxing I do \BLANK.", id: 11 },
    { content: "High quality software is made with \BLANK", id: 12 },
    { content: "I am using \BLANK for my monolith.", id: 1 },
    { content: "I asked my boss for a raise due to \BLANK.", id: 13 },
    { content: "I declined the pull request because of \BLANK.", id: 14 },
    { content: "I destroyed \BLANK by \BLANK.", id: 15 },
    { content: "I don't get laid because of \BLANK.", id: 16 },
    { content: "I don't get paid because of \BLANK.", id: 17 },
    { content: "I don't need backups, I have \BLANK.", id: 18 },
    { content: "I filed a bug on \BLANK.", id: 19 },
    { content: "I had a problem with \BLANK and solved it by \BLANK.", id: 20 },
    { content: "I integrated \BLANK into my DevSecOps pipeline.", id: 21 },
    { content: "I like to get drunk and \BLANK.", id: 1 },
    { content: "I like to turn up to investor meetings \BLANK.", id: 22 },
    { content: "I spent my last salary on \BLANK.", id: 23 },
    { content: "I successfully tested \BLANK.", id: 24 },
    { content: "I switched to Linux because of \BLANK.", id: 25 },
    { content: "I would sell my shares of the company for \BLANK.", id: 26 },
    { content: "Last deployment failed because of \BLANK.", id: 27 },
    { content: "Last time I went outside, I experienced \BLANK.", id: 28 },
    { content: "Last year North Korea spent 10 million on \BLANK.", id: 29 },
    { content: "My Cloud Drive won't sync because of \BLANK.", id: 30 },
    { content: "My alternative to the gym is \BLANK.", id: 31 },
    { content: "My co-worker files a complaint because of \BLANK.", id: 32 },
    { content: "My currently relationship status is \BLANK because of \BLANK.", id: 33 },
    { content: "My job feels like \BLANK.", id: 34 },
    { content: "My morning toilet session can be explained as \BLANK.", id: 35 },
    { content: "My security is so good, it \BLANK.", id: 36 },
    { content: "On my GitHub profile you will find \BLANK.", id: 37 },
    { content: "On our Offsite we did \BLANK.", id: 38 },
    { content: "Our USP is \BLANK.", id: 39 },
    { content: "Our systems for \BLANK runs only on raspberry pies.", id: 40 },
    { content: "Software development is like \BLANK.", id: 41 },
    { content: "The 11-star user experience is \BLANK.", id: 42 },
    { content: "The booth is themed \BLANK.", id: 43 },
    { content: "The customer requests \BLANK.", id: 44 },
    { content: "The difference between RSA and DSA is \BLANK.", id: 45 },
    { content: "The documentation says you should \BLANK, but to make it work you need to \BLANK.", id: 46 },
    { content: "The new marketing campaign for April 1st will be \BLANK.", id: 47 },
    { content: "The next blog article will be about \BLANK.", id: 48 },
    { content: "The next superior cloud service will use \BLANK.", id: 49 },
    { content: "There still is a bug in \BLANK.", id: 50 },
    { content: "This year's marketing motto is \BLANK.", id: 51 },
    { content: "We use \BLANK for quality control.", id: 52 },
    { content: "When the marketing intern asks: 'Can you please change \BLANK on the website'", id: 53 },
    { content: "When the sales guys are laughing in their office they are \BLANK.", id: 54 },
    { content: "Yesterday Bill Gates asked me \BLANK", id: 55 },
    { content: "\BLANK as a Service", id: 56 },
    { content: "\BLANK makes the CEO happy.", id: 57 },
    { content: "\BLANK. How did this ever work?", id: 58 },
    { content: "\BLANK. Oh, this was earlier than expected.", id: 59 },
];

export default blackCards;