import { Card } from "../types";

const whiteCards: Card[] = [
    { content: "'Did you try turning it off and on again?'", id: 1 },
    { content: "'I destroyed the internet'", id: 2 },
    { content: "'I tested it'", id: 3 },
    { content: "'Your' opinion", id: 4 },
    { content: "45 minutes daily standup", id: 5 },
    { content: "A fridge filled with club mate", id: 6 },
    { content: "A missing semicolon", id: 7 },
    { content: "A short nap", id: 8 },
    { content: "A three day build pipeline", id: 9 },
    { content: "A/B testing", id: 10 },
    { content: "AI Hackathon", id: 11 },
    { content: "AI based sex toys", id: 12 },
    { content: "An oversized office chair", id: 13 },
    { content: "Backdoor Traffic", id: 14 },
    { content: "Beer Pong as a team event", id: 15 },
    { content: "Beer in the office", id: 16 },
    { content: "Being oddly specific", id: 17 },
    { content: "Big Data driven business model", id: 18 },
    { content: "Bill Gates", id: 19 },
    { content: "Black holes", id: 20 },
    { content: "Blinking ads", id: 21 },
    { content: "Browsing StackOverflow for hours without actually looking for a solution", id: 22 },
    { content: "Bruce Schneier", id: 23 },
    { content: "Burger Tuesday", id: 24 },
    { content: "CORS Headers", id: 25 },
    { content: "Cat videos", id: 26 },
    { content: "Church of the flying spaghetti monster", id: 27 },
    { content: "Code monkeys", id: 28 },
    { content: "Cold leftover pizza from last week", id: 29 },
    { content: "Comic Con", id: 30 },
    { content: "Commenting it out", id: 31 },
    { content: "Compilation error", id: 32 },
    { content: "Copy \& Pasting from StackOverflow", id: 33 },
    { content: "Creating a buffer overflow", id: 34 },
    { content: "Cuddling with ewoks", id: 35 },
    { content: "Customer touchpoints", id: 36 },
    { content: "Darknet Marketplace", id: 37 },
    { content: "Darude Sandstorm", id: 38 },
    { content: "Day Drinking", id: 39 },
    { content: "Deleting one cell in Excel wrathing your whole data model", id: 40 },
    { content: "Deodorant instead of showers", id: 41 },
    { content: "DevOps Engineers", id: 42 },
    { content: "DevSecOps", id: 43 },
    { content: "Displaying success messages in red color to scare the hell out of others", id: 44 },
    { content: "Don't lick it", id: 45 },
    { content: "Donald Trump", id: 46 },
    { content: "Dry humping", id: 47 },
    { content: "Ejecting USB drives unsafely", id: 48 },
    { content: "Elon Musk", id: 49 },
    { content: "End to end encryption with a non-revocable static key", id: 50 },
    { content: "Explosive diarrhea", id: 51 },
    { content: "Fair hostesses", id: 52 },
    { content: "Fast food, five times a week", id: 53 },
    { content: "Fixing bugs during the penetration test", id: 54 },
    { content: "Forget to lock my computer", id: 55 },
    { content: "Going to prom naked", id: 56 },
    { content: "Hacker bootcamp", id: 57 },
    { content: "Hacking Vibrators", id: 58 },
    { content: "Having the last word", id: 59 },
    { content: "Hoodies and Ski masks", id: 60 },
    { content: "It is always a good idea to change a running system", id: 61 },
    { content: "It worked on staging", id: 62 },
    { content: "It's a feature", id: 63 },
    { content: "Just a minor refactoring", id: 64 },
    { content: "KISS", id: 65 },
    { content: "Layer 8 problem", id: 66 },
    { content: "Leaving the backdoor open", id: 67 },
    { content: "Legacy Code", id: 68 },
    { content: "Living in my mother's basement", id: 69 },
    { content: "Looking like I care", id: 70 },
    { content: "Lucky13", id: 71 },
    { content: "Magic Numbers", id: 72 },
    { content: "Making small changes in production", id: 73 },
    { content: "Male underboob sweat", id: 74 },
    { content: "Marc Zuckerberg", id: 75 },
    { content: "Microservice Architecture", id: 76 },
    { content: "Minecraft", id: 77 },
    { content: "My lovelife", id: 78 },
    { content: "NAT allergy", id: 79 },
    { content: "Not wearing pants during video chats", id: 80 },
    { content: "Null pointer exception", id: 81 },
    { content: "Nyan Cat", id: 82 },
    { content: "Old people smell", id: 83 },
    { content: "Opening an alpaca farm", id: 84 },
    { content: "Outsourcing to India", id: 85 },
    { content: "Overspecified requirements", id: 86 },
    { content: "PHP", id: 87 },
    { content: "Panda porn", id: 88 },
    { content: "Penetration without testing", id: 89 },
    { content: "Playing Mario cart.... in single player mode", id: 90 },
    { content: "Please beautify", id: 91 },
    { content: "Plugging in a USB drive correctly the first time", id: 92 },
    { content: "Plumber's smile", id: 93 },
    { content: "Popping the stack", id: 94 },
    { content: "Python", id: 95 },
    { content: "Quadrocopter with infrared camera", id: 96 },
    { content: "Quick fix", id: 97 },
    { content: "Quick search", id: 98 },
    { content: "Quoting the Big Bang Theory", id: 99 },
    { content: "Reading the Youporn blog entries on technology for research purposes", id: 100 },
    { content: "Rebasing", id: 101 },
    { content: "Releasing features early", id: 102 },
    { content: "Releasing too early", id: 103 },
    { content: "Remote access", id: 104 },
    { content: "Reviewing pull requests", id: 105 },
    { content: "Rooftop barbecue party", id: 106 },
    { content: "Running a conference completely with volunteers", id: 107 },
    { content: "STDs", id: 108 },
    { content: "Scope Creep", id: 109 },
    { content: "Script Kiddy", id: 110 },
    { content: "Server farms", id: 111 },
    { content: "Shared Memory", id: 112 },
    { content: "Smiling a little bit too much", id: 113 },
    { content: "Software rollback", id: 114 },
    { content: "Something written in Fortran", id: 115 },
    { content: "Steve Jobs", id: 116 },
    { content: "Stormtroopers for quality control", id: 117 },
    { content: "Sun rays", id: 118 },
    { content: "Swinging my light saber", id: 119 },
    { content: "Swiping left and right", id: 120 },
    { content: "Technical Difficulties", id: 121 },
    { content: "Ten layered if statements", id: 122 },
    { content: "Terraforming", id: 123 },
    { content: "Testing early", id: 124 },
    { content: "Testing in production", id: 125 },
    { content: "That can't be too complicated", id: 126 },
    { content: "The 16th internship in the 12th company", id: 127 },
    { content: "The Linux Kernel", id: 128 },
    { content: "The dark side of the force", id: 129 },
    { content: "The difference between machine learning and AI", id: 130 },
    { content: "Tinder newsletter", id: 131 },
    { content: "Tiny student dorms", id: 132 },
    { content: "Too many hot girls", id: 133 },
    { content: "Touch control", id: 134 },
    { content: "Touching my joystick", id: 135 },
    { content: "Touching myself", id: 136 },
    { content: "Tripping the wire", id: 137 },
    { content: "Unexpected side effects", id: 138 },
    { content: "Unicorns", id: 139 },
    { content: "Useless meeting", id: 140 },
    { content: "User space function calls", id: 141 },
    { content: "Using Blockchain instead of a database", id: 142 },
    { content: "Using HTML as a programming language", id: 143 },
    { content: "Using Tabs instead of Spaces", id: 144 },
    { content: "Using XML instead of JSON", id: 145 },
    { content: "Using a light theme for the terminal", id: 146 },
    { content: "Using blockchain in every pitch", id: 147 },
    { content: "Using kubernetes for my static website with 100 visitors per month", id: 148 },
    { content: "Using more than 10 programming languages because I can", id: 149 },
    { content: "Using open source software just because it's free", id: 150 },
    { content: "Vendor lock Stockholm syndrome", id: 151 },
    { content: "Watching Porn over the company vpn", id: 152 },
    { content: "Whistling the Tetris theme song", id: 153 },
    { content: "Winking at old people", id: 154 },
    { content: "Winning because of psychological warfare", id: 155 },
    { content: "Writing code without my supervisor telling me what to do", id: 156 },
    { content: "\LaTeX", id: 157 },
    { content: "git --force push", id: 158 },
    { content: "iOS developers", id: 159 },
    { content: "in $O(1)$", id: 160 },
    { content: "rm -rf /", id: 161 },
    { content: "sudo", id: 162 },
];

export default whiteCards;
